In [81]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [82]:
data = pd.read_csv('E:\CreditCard_Dataset\creditcard.csv')
data.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [83]:
data.shape

(284807, 31)

In [84]:
data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [85]:
data['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [86]:
(492/284807) * 100

0.1727485630620034

In [87]:
## Dependent and Independent Features

X = data.drop('Class', axis=1)
y = data.Class

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=0)

### Cross Validation like KFold and Hyperparameter Tuning

In [88]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import KFold #Cross Validation
from sklearn.model_selection import GridSearchCV #Hyperparameter Tuning

In [89]:
log_class = LogisticRegression()
grid = {'C':10.0 ** np.arange(-2,3), 'penalty': ['l1','l2']}

cv = KFold(n_splits=5, shuffle=False, random_state=None)

In [90]:
clf = GridSearchCV(log_class, grid, cv=cv, n_jobs=-1, scoring='f1_macro')
clf.fit(X_train, y_train)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [91]:
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85262    34]
 [   52    95]]
0.9989934810341398
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.74      0.65      0.69       147

    accuracy                           1.00     85443
   macro avg       0.87      0.82      0.84     85443
weighted avg       1.00      1.00      1.00     85443



In [93]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)

RandomForestClassifier()

In [94]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85291     5]
 [   34   113]]
0.9995435553526912
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.96      0.77      0.85       147

    accuracy                           1.00     85443
   macro avg       0.98      0.88      0.93     85443
weighted avg       1.00      1.00      1.00     85443



### Under Sampling

* Reduce the points of the maximum labels.

In [96]:
from collections import Counter
print(Counter(y_train))

Counter({0: 199019, 1: 345})


In [108]:
from imblearn.under_sampling import NearMiss
from collections import Counter

ns = NearMiss(sampling_strategy='auto')
X_train_ns, y_train_ns = ns.fit_resample(X_train, y_train)

print("The number of classes before the fit: {}".format(Counter(y_train)))
print("The number of classes after the fit: {}".format(Counter(y_train_ns)))

AttributeError: 'NoneType' object has no attribute 'split'

In [109]:
from imblearn.over_sampling import RandomOverSampler

In [111]:
os = RandomOverSampler(sampling_strategy=0.8)
X_train_os, y_train_os = os.fit_resample(X_train, y_train)

print("The number of classes before the fit: {}".format(Counter(y_train)))
print("The number of classes after the fit: {}".format(Counter(y_train_os)))

The number of classes before the fit: Counter({0: 199019, 1: 345})
The number of classes after the fit: Counter({0: 199019, 1: 159215})


In [112]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train_os, y_train_os)

RandomForestClassifier()

In [113]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85290     6]
 [   33   114]]
0.9995435553526912
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.95      0.78      0.85       147

    accuracy                           1.00     85443
   macro avg       0.97      0.89      0.93     85443
weighted avg       1.00      1.00      1.00     85443



### SMOTE Tomek

In [134]:
## It creates new points
from imblearn.combine import SMOTETomek

In [137]:
sm = SMOTETomek(sampling_strategy=0.5)
X_train_sm, y_train_sm = sm.fit_resample(X_train, y_train)

print("The number of classes before the fit: {}".format(Counter(y_train)))
print("The number of classes after the fit: {}".format(Counter(y_train_sm)))

AttributeError: 'NoneType' object has no attribute 'split'

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train_os, y_train_os)